info:
  description: PC ACP Config Server
  url: https://stash.synchronoss.net:8443/users/dfre0002/repos/pc-config/browse
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

