eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery.credentials.uri:http://127.0.0.1:8761}/eureka/

---
# For deployment in Cloud Foundary
spring:
  profiles: cloud
  rabbitmq:
    host: ${vcap.services.cloudbus-amqp.credentials.uri}
    
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80

---
# For deployment in Docker containers
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

