eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    # Default values comes from org.springframework.cloud.netflix.eureka.EurekaClientConfigBean
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5

---
# For deployment in Cloud Foundary
spring:
  profiles: cloud
  rabbitmq:
    host: ${vcap.services.cloudbus-amqp.connection.uri}
    username: ${vcap.services.cloudbus-amqp.connection.username}
    password: ${vcap.services.cloudbus-amqp.connection.password}

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery.credentials.uri:http://127.0.0.1:8761}/eureka/
    
---
# For deployment in Docker containers
spring:
  profiles: docker
  rabbitmq:
    host: rabbitmq

eureka:
  instance:
    preferIpAddress: true
