info:
  component: Service API

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    api:
      path: /api/**
#    pc-core-dv:
#      path: /dv/**
#    pc-core-osg:
#      path: /osg/**
#    pc-core-sal:
#      path: /sal/**

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

