info:
  component: Service API

server:
  port: ${PORT:8765}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    api:
      path: /api/**

logging:
  level:
    ROOT: INFO
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
